version: 2
updates:
- package-ecosystem: docker
  directory: "/auto-tag"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/flask"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/fluentbit"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fluent/fluent-bit
    versions:
    - 1.6.10
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: golang
    versions:
    - 1.15.7
    - 1.15.8
    - 1.16.0
    - 1.16.2
- package-ecosystem: docker
  directory: "/geodesic-base"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/git-secrets"
  schedule:
    interval: weekly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.0
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
