kind: pipeline
name: default

clone:
  depth: 1

#steps:
#  - name: tag
#    image: gcr.io/niki-ai/auto-tag
#    commands:
#      - make init deps lint bash/fmt/check
#
#  - name: publish
#    image: plugins/gcr
#    settings:
#      auto_tag: true
#      registry: gcr.io
#      daemon_experimental: true
#      repo: niki-ai/geodesic
#      #      tags:
#      #        - ${DRONE_COMMIT_SHA}
#      #        - latest
#      cache: true
#      squash: true
#      experimental: true
#      json_key:
#        from_secret: gcr_json_key
#
#trigger:
#  branch:
#    - master
#  event:
#    - push