version: 1

update_configs:
  - package_manager: "docker"
    directory: "auto-tag"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "flask"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "fluentbit"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "geodesic-base"
    update_schedule: "weekly"
  - package_manager: "docker"
    directory: "git-secrets"
    update_schedule: "weekly"
